### PR TITLE
Add some tests for CompressorHead

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #16

### CODE REVIEW

**Comment by zwliew** [comment]
The indentation seems a bit inconsistent here. I believe that the conventional indentation style uses 4 spaces per indent.

**Comment by Androbin** [comment]
@zwliew I am sorry, I have mistakenly mixed tabs and spaces. Gimme a moment to fix this.

**Comment by Androbin** [comment]
@zwliew Sorry, mixed tabs with spaces. Should be consistently 4 spaces now.

**Comment by Androbin** [comment]
Shall we merge or close this?

**Comment by opticod** [comment]
Testing it @Androbin, will update you shortly.

**Comment by opticod** [comment]
Going through it @Androbin, will update you shortly.

**Comment by opticod** [comment]
@Androbin 
The tests are all failing. Possible reason of it:
- You are using `URI`, which is a class and is not implemented by default in the dev jar.
So one possibility is to use [Roboelectric](https://github.com/robolectric/robolectric) or Android [Instrumentation Tests](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests.html). 

You can also go through the links I had posted with the original issue.

**Comment by garg-anuj** [comment]
Please reopen when working

**Pull request closed without merging**
