### PR TITLE
Fix travis config

### PR DESCRIPTION
**Pull request by zwliew**
Oops, my bad.

### CODE REVIEW

**Comment by zwliew** [comment]
Oops, overwrote your changes to change the SDK build tools version. However, I don't think specifying the licenses is needed, since all licenses are accepted by default.

**Comment by garg-anuj** [comment]
@zwliew Felt its old issue from https://github.com/travis-ci/travis-ci/issues/6555

**Comment by garg-anuj** [comment]
@zwliew So you gonna turn off lint of fix all instability?

**Comment by zwliew** [comment]
Yeah, I think so.

**Comment by zwliew** [comment]
I'll ping you again once the change seems ready.

**Comment by garg-anuj** [comment]
okay

**Comment by zwliew** [comment]
@garg-anuj this should be ready now.

**Comment by garg-anuj** [comment]
thanks @zwliew

**Pull request merged**
