### PR TITLE
GCI Task: Put all hardcoded constants into constants file & removed hardcoded strings

### PR DESCRIPTION
**Pull request by Danki567**

### CODE REVIEW

**Comment by m-murad** [comment]
Why are you renaming strings like`imageurl ` to `imageurl2 `.
Don't do this.
Just add translations.

**Comment by Danki567** [comment]
For the task I am not supposed to translate anything. I am just supposed to remove hardcoded strings; which was already done. So I renamed them.

**Comment by Danki567** [comment]
Ok, I fixed it.

**Comment by zwliew** [comment]
The hardcoded strings have already been moved in PR #38. That task is not really applicable to this project anymore.

**Comment by Danki567** [comment]
Ok so what will happen with the gci task?

**Comment by zwliew** [comment]
Maybe try finding a different project that contains hardcoded strings (similar to the ones in PR #38), and softcode them?

**Comment by zwliew** [comment]
You could also try task [6296735494176768](https://codein.withgoogle.com/tasks/6296735494176768) instead, which requires you to translate the existing [strings resources](https://github.com/jboss-outreach/compressor-head-android/blob/master/app/src/main/res/values/strings.xml) to a different language. You can refer to PR #38 for an example on how to do that.

**Comment by Danki567** [comment]
Ok well can I have this one accepted because I did it 2 days ago and asked how to submit. While I waited for an answer someone else did the task.

**Comment by Danki567** [comment]
Thank you for accepting it. I will do the translating one next

**Pull request merged**
